### ISSUE TITLE
Open/close not working

### ISSUE THREAD

**Issue by geritol** [samcorcos/meteor-react-ionic-tabs-modals#1]
Hi! awesome work. I just somehow cant get modals to open on mobile. And if i manage to do so I cant close them. My main problem is closing them. Can you recomend any solutions? Repo deployed here: http://react-modals-test.meteor.com Thanks a lot!

**Comment by samcorcos** [comment]
Yup! So the issue is that you need to change `cursor: pointer` on anything that you want to make touchable on mobile. Also, for additional touch events, you need to add `React.initializeTouchEvents(true)`.

Hope that helps!

**Comment by geritol** [comment]
Thanks!
couldt get it to work with cursor: pointer.
Trying to add some touch events

**Comment by geritol** [comment]
Tryed onTouchStart too but not working :/

**Comment by geritol** [comment]
Added animation to it and somehow got it to work!
Weird bug in react, they say 0.14 gets it fixed.
Thanks a lot!

**Comment by samcorcos** [comment]
@geritol No problem :)
